### ISSUE TITLE
Putout prevents ESLint from running

### ISSUE THREAD

**Issue by brunoparga** [coderaiser/putout#90] opened 2021-11-22 11:06 UTC
Hello! I am facing an issue with putout. In my Angular project, I would like to use it as part of [hardcore](https://github.com/EvgenyOrekhov/eslint-config-hardcore). I am using the latest version, which requires version ^11.7.0 of `eslint-plugin-putout`. My Node version is 16.11.1.

I am creating the issue here because ESLint works just fine when I disable the 'putout/putout' rule. When it is enabled, I get this error:

```
$ npx eslint --fix --ext .ts,.html,.js ./src/app
Oops! Something went wrong! :(

ESLint: 8.2.0

Error: { type: TSClassImplements, expression: [object Object], range: 683,689, loc: [object Object], parent: [object Object] } does not match type Printable
Occurred while linting my_project/src/app/aaaafoo/aaaafoo.component.ts:1
Rule: "putout/putout"
    at PredicateType.BaseType.assert (my_project/node_modules/ast-types/lib/types.js:14:19)
    at genericPrintNoParens (my_project/node_modules/@putout/recast/lib/printer.js:160:26)
    at genericPrint (my_project/node_modules/@putout/recast/lib/printer.js:123:30)
    at print (my_project/node_modules/@putout/recast/lib/printer.js:77:15)
    at my_project/node_modules/@putout/recast/lib/printer.js:49:41
    at printComments (my_project/node_modules/@putout/recast/lib/comments.js:281:22)
    at print (my_project/node_modules/@putout/recast/lib/printer.js:55:49)
    at my_project/node_modules/@putout/recast/lib/printer.js:49:41
    at FastPath.map (my_project/node_modules/@putout/recast/lib/fast-path.js:171:25)
    at genericPrintNoParens (my_project/node_modules/@putout/recast/lib/printer.js:1130:84)
```

As you can see, the error message singles out putout as the rule that's causing the issue. This happens at the very first line of the very first file of the very first directory in my project, which leads me to suspect this is a global problem rather than specific to that file.

Do you have any ideas, or requests for how to make my question clearer and help you help me?

**Comment by coderaiser** [comment] 2021-11-22 12:23
Could you please provide code example, and minimal possible confit you using. Looks like it’ related to classes and typescript according to `TSClassImplements` node type.

**Comment by coderaiser** [comment] 2021-11-22 13:08
That's right, this is [@typescript-eslint/typescript-estree](https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/typescript-estree):

![image](https://user-images.githubusercontent.com/1573141/142867220-0f24c150-8fb1-4806-aa45-0feba90c969f.png)

**Comment by coderaiser** [comment] 2021-11-22 13:24
Landed in [estree-to-babel v4.4.0](https://github.com/coderaiser/estree-to-babel/releases/tag/v4.4.0) 🎉 .
Please re-install 🐊`Putout`. Is it works for you?

**Comment by brunoparga** [comment] 2021-11-22 16:03
Hi! Thank you so much for the prompt reply. However, it unfortunately still doesn't work, even though I've updated both `eslint-plugin-putout` and `estree-to-babel`. I still get the same error. It is worth pointing out that you are correct about me using typescript-eslint.

Since my project depends on putout by means of hardcore, I will reference this issue on their repository.

**Comment by brunoparga** [comment] 2021-11-22 16:38
I will also try to create a reproduction repo by tomorrow.

**Comment by coderaiser** [comment] 2021-11-24 09:56
I can’t reproduce this after fix, so I close. If you can provide more information feel free to reopen.

**Closed by coderaiser** 2021-11-24 09:56 UTC
Labels: bug, eslint-plugin-putout, typescript
