### ISSUE TITLE
http://putout.cloudcmd.io/ fails to load with error "TypeError: t.iter is not a function"

### ISSUE THREAD

**Issue by sgilroy** [coderaiser/putout#8] opened 2019-08-30 15:22 UTC
When trying to navigate to http://putout.cloudcmd.io/ there is a JavaScript error and the page fails to load. The only visible content is a contribution footer. The link http://putout.cloudcmd.io/ appears in the description for the GitHub project https://github.com/coderaiser/putout/, so it may be one of the first links that a potential user will look at when exploring the project.

Tested in Chrome and Firefox. The error below is from Chrome Version 76.0.3809.100 (Official Build) (64-bit)
```
vendors~app-be21591da1b5607b3eb3-26.js:50 TypeError: t.iter is not a function
    at estimateLineHeights (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at attachDoc (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at new CodeMirror (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at CodeMirror (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at Editor.componentDidMount (app-6544ad61fc0ebc2847bb-26.js:2167)
    at nj (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at t.unstable_runWithPriority (vendors~app-be21591da1b5607b3eb3-26.js:9)
    at vf (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at ij (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at eg (vendors~app-be21591da1b5607b3eb3-26.js:50)
di @ vendors~app-be21591da1b5607b3eb3-26.js:50
vendors~app-be21591da1b5607b3eb3-26.js:50 Uncaught TypeError: t.iter is not a function
    at estimateLineHeights (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at attachDoc (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at new CodeMirror (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at CodeMirror (vendors~app-be21591da1b5607b3eb3-26.js:19)
    at Editor.componentDidMount (app-6544ad61fc0ebc2847bb-26.js:2167)
    at nj (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at t.unstable_runWithPriority (vendors~app-be21591da1b5607b3eb3-26.js:9)
    at vf (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at ij (vendors~app-be21591da1b5607b3eb3-26.js:50)
    at eg (vendors~app-be21591da1b5607b3eb3-26.js:50)
app-6544ad61fc0ebc2847bb-26.js:2167 Unable to write to local storage.
i @ app-6544ad61fc0ebc2847bb-26.js:2167
```

**Comment by coderaiser** [comment] 2019-09-02 10:35
I can't reproduce this, everything works good for me, could you please try clear cache or use incognito mode?

**Comment by coderaiser** [comment] 2019-09-02 13:30
Thank you, fixed with https://github.com/coderaiser/putout-editor/commit/a4c836d42f3c73658f211e57eb6eb991b8ddf075.

Is it works for you?

**Closed by coderaiser** 2019-09-02 13:30 UTC
Labels: bug

**Comment by sgilroy** [comment] 2019-09-02 23:40
@coderaiser Yes, the page https://putout.cloudcmd.io/ loads without errors for me now. Thanks for the fix!
